Pos addons 12.0 pos network printer iot
it-projects-llc/addons-dev pull request #734
Opened 2019-09-25 12:02 UTC by KolushovAlexandr

2019-09-30 06:58 UTC, Ramil-Mukhametzyanov requested changes

2019-09-30 06:58 UTC, Ramil-Mukhametzyanov commented on pos_printer_network_iot/doc/changelog.rst
> +- **Init version**
The IP-address field is not editable

2019-09-30 12:52 UTC, Ramil-Mukhametzyanov requested changes
Can not print on network order printer

![image](https://user-images.githubusercontent.com/33877236/65880179-db051680-e3aa-11e9-9992-315ac81dd85c.png)

![image](https://user-images.githubusercontent.com/33877236/65880155-cd4f9100-e3aa-11e9-8b70-1f8a500d375d.png)

![image](https://user-images.githubusercontent.com/33877236/65880281-fa9c3f00-e3aa-11e9-89d0-48b5bed5b18e.png)

2019-09-30 12:58 UTC, Ramil-Mukhametzyanov reviewed
http://192.168.1.126:8069/hw_proxy/status_network_printers?session_id=
Response:
{"result": [{"ip": "192.168.1.126", "status": "online", "name": "Printer"}, {"ip": "192.168.1.169", "status": "online", "name": "Kitchen Printer"}], "jsonrpc": "2.0", "id": 767669322}

2020-05-12 07:50 UTC, yelizariev commented
The modules seems be merged to pos-addons

2020-05-12 07:50 UTC, closed without merging

2020-05-12 07:51 UTC, yelizariev commented
I'm wront. IOT module is note published in pos-addons